---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: pavankumarsangisetti/homepagerepo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7003
